=== gmeza-com/baohaiquan/shadcn.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "style": {
      "type": "string",
      "enum": ["default", "new-york"]
    },
    "tailwind": {
      "type": "object",
      "properties": {
        "config": {
          "type": "string"
        },
        "css": {
          "type": "string"
        },
        "baseColor": {
          "type": "string"
        },
        "cssVariables": {
          "type": "boolean"
        },
        "prefix": {
          "type": "string"
        }
      },
      "required": ["config", "css", "baseColor", "cssVariables"]
    },
    "rsc": {
      "type": "boolean"
    },
    "tsx": {
      "type": "boolean"
    },
    "iconLibrary": {
      "type": "string"
    },
    "aliases": {
      "type": "object",
      "properties": {
        "utils": {
          "type": "string"
        },
        "shadcn": {
          "type": "string"
        },
        "ui": {
          "type": "string"
        },
        "lib": {
          "type": "string"
        }
      },
      "required": ["utils", "shadcn"]
    }
  },
  "required": ["style", "tailwind", "rsc", "aliases"]
}

=== gmeza-com/baohaiquan/components.json
{
  "$schema": "shadcn.schema.json",
  "style": "new-york",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "",
    "css": "src/app/globals.css",
    "baseColor": "neutral",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "shadcn": "@/shadcn",
    "utils": "@/lib/utils",
    "ui": "@/shadcn/ui",
    "lib": "@/lib"
  },
  "iconLibrary": "lucide"
}
